### ISSUE TITLE
Internal Database Error in wsfev1.py

### ISSUE THREAD

**Issue by chazuttu** [PyAr/pyafipws#70]
On execution the command in the **main** branch:

`$ wsfev1 --parametros`

the following output is received:
```
=== Tipos de Paises ===
FEParamGetTiposPaises'}}]}}
Traceback (most recent call last):
  File "C:\Users\pyafipws\py3\Scripts\wsfev1-script.py", line 33, in <module>
    sys.exit(load_entry_point('PyAfipWs===3.9.b-2522-', 'console_scripts', 'wsfev1')())
  File "C:\Users\\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\wsfev1.py", line 1570, in main
    print(u"\n".join(wsfev1.ParamGetTiposPaises()))
  File "C:\Users\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\utils.py", line 201, in capturar_errores_wrapper    
    return func(self, *args, **kwargs)
  File "C:\Users\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\wsfev1.py", line 1228, in ParamGetTiposPaises       
    for p in res["ResultGet"]
KeyError: 'ResultGet'
```

on checking the return value **ret**, we find:
`ret------ {'FEParamGetTiposPaisesResult': {'Errors': [{'Err': {'Code': 501, 'Msg': 'Error interno de base de datos: - Metodo `

This seems to be an internal error, causing the failure for **Tipos se Paises** parameter.

**Comment by baivab85** [comment]
I think this code can fix it

def ParamGetTiposPaises():
    try:
        res = some_function_that_returns_dictionary() 
        tipos_paises = res.get("ResultGet", [])  
        for p in tipos_paises:
            pass
        return tipos_paises  
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

**Comment by ghost** [comment]
I think this code can fix it

def ParamGetTiposPaises():
try:
res = some_function_that_returns_dictionary()
tipos_paises = res.get("ResultGet", [])
for p in tipos_paises:
pass
return tipos_paises
except Exception as e:
print(f"An error occurred: {e}")
return []
