### ISSUE TITLE
Server null error in wsct.py

### ISSUE THREAD

**Issue by chazuttu** [PyAr/pyafipws#83]
Many command line options in wsct.py give the following error:-

`pysimplesoap.client.SoapFault: S:Server: null`

Complete error:-
`$ wsct --parametros`

```
para soporte de WebClient debe instalar httplib2
Creando TRA...
Firmando TRA...
Conectando a WSAA...
Llamando WSAA...
Grabando TA en C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\cache\TA-eaf252cfe0cca095fa0a172613f19f25.xml...
Traceback (most recent call last):
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\Scripts\wsct-script.py", line 33, in <module>
    sys.exit(load_entry_point('PyAfipWs===3.9.b-2522-', 'console_scripts', 'wsct')())
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\wsct.py", line 1128, in main
    print(wsct.ConsultarTiposDatosAdicionales())
  File "C:\Users\\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\utils.py", line 201, in capturar_errores_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pyafipws-3.9.b_2522_-py3.9.egg\pyafipws\wsct.py", line 871, in ConsultarTiposDatosAdicionales
    ret = self.client.consultarTiposDatosAdicionales(
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pysimplesoap\client.py", line 159, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr,*args,**kwargs)
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pysimplesoap\client.py", line 354, in wsdl_call
    response = self.call(method, types, *params)
  File "C:\Users\Desktop\GSoC_online\pyafipws\py3\lib\site-packages\pysimplesoap\client.py", line 234, in call
    raise SoapFault(str(response.faultcode), str(response.faultstring))
pysimplesoap.client.SoapFault: S:Server: null
```

**Comment by baivab85** [comment]
The error message you're seeing is a SoapFault error, which is typically thrown when there's an issue with the SOAP request being sent to the server. In this case, the error message is S:Server: null, which suggests that the server is returning a null response.

Here are a few things you can try to resolve this issue:

Check the server URL: Ensure that the server URL you're using is correct. If the URL is incorrect, the server might not be able to process your request, leading to a null response.

Check the SOAP request: The issue might be with the SOAP request you're sending. Make sure that the request is properly formatted and contains all the necessary information.

Check the server status: The server might be down or experiencing issues. If this is the case, you might need to wait until the server is up and running again.

Update your dependencies: The issue might be caused by outdated or incompatible dependencies. Try updating your dependencies to the latest versions.

If none of these solutions work, you might need to reach out to the server administrator or the support team for the SOAP service you're using for further assistance.

**Comment by RohitP2005** [comment]
Hey @reingart  I am willing to work on it if its still available
